# file: install-rhv-tools.yml
#
# $ ansible-playbook install-rhv-tools.yml --inventory 192.168.0.99,
#                                                    ^^^ notice trailing comma
# $ ansible-playbook install-rhv-tools.yml --ask-vault-pass -u root -k -i 192.168.0.54, --list-tasks
# $ ansible-playbook install-rhv-tools.yml --limit rhel-srv01

---
- hosts: all
  roles:
    - install-rhv-tools
