# file: ocp-rpm-preinstall.yml
# Author: Mike Flannery (mflanner@redhat.com) & John Call (jcall@redhat.com)
# invocation: ansible-playbook ocp-rpm-preinstall.yml

# https://access.redhat.com/documentation/en-us/openshift_container_platform/3.7/html-single/installation_and_configuration/#install-config-install-advanced-install

---
- hosts: all
  become: true
  vars: 
    repos: #dynamically populated below

#  vars_prompt:
#    - name: "rhsm_username"
#      prompt: "Enter RHN/RHSM Username"
#      private: no
#
#    - name: "rhsm_password"
#      prompt: "Enter RHN/RHSM Password"
#      private: yes
#
#    - name: "poolid"
#      prompt: "Enter Red Hat Pool ID"
#      private: no

  tasks:
  - name: Register with Red Hat
    redhat_subscription:
      state: present
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
      autosubscribe: false
    async: 300
    poll: 10
    tags:
      - rhsm

  - name: Attach Pool
    command: subscription-manager attach --pool={{ poolid }}
    async: 300
    poll: 10
    tags:
      - rhsm

  - block:
    - set_fact:
        repos: "{{ repos }} --enable={{ item }}"
      no_log: true
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        #- rhel-7-server-optional-rpms
        #- rhel-7-server-supplementary-rpms
        - rhel-7-server-ose-3.7-rpms
        - rhel-7-fast-datapath-rpms
        #- rh-gluster-3-for-rhel-7-server-rpms # disabled because it provides a shit version of python-requests, and we don't need it anyway because RHGS is installed via containers
        - rh-gluster-3-client-for-rhel-7-server-rpms

    - debug:
        var: repos

    - name: Disable all repos
      command: subscription-manager repos --disable="*"

    - name: Enable repos
      command: subscription-manager repos {{ repos }} 

    tags:
      - repos
    when: ansible_distribution_major_version == "7" #end block

  - name: Install required RPMs
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - atomic-openshift-utils
    tags:
      - rpms

#  - name: Reboot to apply any updates, and clear cloud-init state
#    command: systemctl reboot
#    tags: reboot
