# file: redhat-register-single-file.yml
# $ ansible-playbook redhat-register-single-file.yml --ask-vault-pass -u root -k

---
- hosts: all
  vars:
    employee_sku_physical: 8a85f981571fb49101571fc414470a43
    employee_sku_virtual: 8a85f981571fb49101571fc415340afb
  vars_prompt:
    - prompt: "Enter RHN/RHSM Username"
      name: "rhsm_user"
      private: no
    - prompt: "Enter RHN/RHSM Password"
      name: "rhsm_pass"
      private: yes
  tasks:
    - name: Register with Red Hat
      redhat_subscription: state=present
                           username={{ rhsm_user }}
                           password={{ rhsm_pass }}
                           autosubscribe=false
    
    - name: Attach my Employee Subscription (physical)
      command: subscription-manager attach --pool={{ employee_sku_physical }}
      when: ansible_virtualization_role != "guest"
    
    - name: Attach my Employee Subscription (virtual)
      command: subscription-manager attach --pool={{ employee_sku_virtual }}
      when: ansible_virtualization_role == "guest"
    
    - name: Disable all repos
      command: subscription-manager repos --disable="*"
    
    - name: Enable repo for RHEL 7
      command: subscription-manager repos --enable="rhel-7-server-rpms"
      when: ansible_distribution_major_version == "7"
    
    - name: Enable repo for RHEL 6
      command: subscription-manager repos --enable="rhel-6-server-rpms"
      when: ansible_distribution_major_version == "6"
    
    - name: Create /var/log/journal directory
      file: path=/var/log/journal state=directory mode=2755 owner=0 group=190 #root:systemd-journal
      when: ansible_distribution_major_version == "7"
