# file: redhat-register-single-file.yml
# $ ansible-playbook redhat-register-single-file.yml --ask-vault-pass -u root -k

---
- hosts: all
  vars:
    employee_sku_physical: 8a85f98a60c09b100160c40fd5ff63dc
    employee_sku_virtual: 8a85f98a60c09b100160c40fd82d63fb
    repos:
  vars_prompt:
    - prompt: "Enter RHN/RHSM Username"
      name: "rhsm_user"
      private: no
    - prompt: "Enter RHN/RHSM Password"
      name: "rhsm_pass"
      private: yes

  tasks:
    - name: Register with Red Hat
      redhat_subscription:
         state: present
         username: "{{ rhsm_user }}"
         password: "{{ rhsm_pass }}"
         autosubscribe: false
      serial: 2
      async: 300
      poll: 10
    
    - name: Attach my Employee Subscription (physical)
      command: subscription-manager attach --pool={{ employee_sku_physical }}
      when: ansible_virtualization_role != "guest"
      serial: 2
      async: 300
      poll: 10
    
    - name: Attach my Employee Subscription (virtual)
      command: subscription-manager attach --pool={{ employee_sku_virtual }}
      when: ansible_virtualization_role == "guest"
      async: 300
      poll: 10
    
    - name: Disable all repos
      command: subscription-manager repos --disable="*"

    - name: Enable repos for RHEL7
      block:
      - set_fact:
          repos: "{{ repos }} --enable={{ item }}"
        with_items:
          - rhel-7-server-rpms
#          - rhel-7-server-extras-rpms
#          - rhel-7-server-optional-rpms
#          - rhel-7-server-supplementary-rpms
#          - rhel-7-server-ose-3.7-rpms
#          - rhel-7-fast-datapath-rpms
#          - rh-gluster-3-client-for-rhel-7-server-rpms
      - debug:
          var: repos
      - command: subscription-manager repos {{ repos }} 
      when: ansible_distribution_major_version == "7"
      tags:
        - repos
    
    - name: Enable repo for RHEL 6
      command: subscription-manager repos --enable="rhel-6-server-rpms"
      when: ansible_distribution_major_version == "6"
    
    - name: Create /var/log/journal directory
      file: path=/var/log/journal state=directory mode=2755 owner=0 group=190 #root:systemd-journal
      when: ansible_distribution_major_version == "7"
