# file: rhv-powerOn.yml
#
# prerequisites:
# $ sudo yum --enablerepo=rhel-7-server-rhv-4.1-rpms install python-ovirt-engine-sdk4
#
# extra-vars:
# $ ansible-playbook rhv-powerOn.yml --ask-vault-pass -e vmName=CHANGEME -e vmState=stopped

---
- hosts: localhost
  gather_facts: no
  vars_files:
  - rhvm-vault.yml

  vars:
    vmState: running
    vmName: CHANGEME
    rhvCluster: Basement

  tasks:
    - name: Create RHV auth token
      ovirt_auth:
        url: https://rhvm.home.lab/ovirt-engine/api
        insecure: yes
        username: "{{ rhvuser }}"
        password: "{{ rhvpass }}"

    - name: Set VM "{{ vmName }}" to state "{{ vmState }}"
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ rhvCluster }}"
        name: "{{ vmName }}"
        state: "{{ vmState }}"

    - name: Remove RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
