---
- name: Rolling upgrade of RHV-H nodes
  hosts: localhost
  gather_facts: yes
  vars:
    choices:
  tasks:
    - find: 
        path: "{{ playbook_dir }}/{{ ansible_domain }}"
        pattern: "*-vars.yml"
      register: result
    - set_fact:
        choices: "{{ choices }} {{ item.path | basename }}"
      with_items: "{{ result.files }}"
      no_log: true
    - debug:
        msg: "Please choose one of these:{{ choices }}"


- hosts: localhost
#- hosts: rhvm
  gather_facts: yes
  vars_prompt:
    - prompt: "Please choose one of the above"
      name: input
      private: no
  vars_files:
    - "{{ ansible_domain }}/{{ input }}"
    - "{{ ansible_domain }}/rhvm-vault.yml"

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ rhvurl }}"
        insecure: yes
        username: "{{ rhvuser }}"
        password: "{{ rhvpass }}"

    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
