# file: roles/gluster-mkswap/tasks/main.yml

---
- name: Make a 2GB file at /swapfile
  command: time dd if=/dev/zero of=/swapfile bs=1M count=2000

- name: Restrict permissions to 0600
  command: chmod 0600 /swapfile

- name: mkswap
  command: mkswap /swapfile

- name: swapon
  command: swapon /swapfile
