# file: roles/install-rhv-tools/tasks/rhel6.yml

---
- name: RHEL6 - Install RHV Guest Agent
  yum:
    name: rhevm-guest-agent-common
    state: latest
    disablerepo: '*'
    enablerepo: rhel-6-server-rpms,rhel-6-server-rhev-agent-rpms

- name: RHEL6 - Enable and start RHV Guest Agent
  service:
    name: ovirt-guest-agent
    enabled: yes
    state: started
